Multiple entities per classification, list sorting
DataBiosphere/tanagra pull request #536
Opened 2023-09-18 19:29 UTC by tjennison-google

* Add support for combining multiple entities within a single classification criteria. This is initially used to combine the LOINC and SNOMED criteria for standard measurements.
* Make data enry merging code more generic. It could likely be moved out of source.tsx in the future.
* Add configuration for the list view in classification criteria separately from the hierarchy views.
* Move IS_MEMBER filter to after the query to allow for better optimization on the back end.

2023-09-19 02:50 UTC, marikomedlock approved these changes

2023-09-19 03:10 UTC, marikomedlock requested changes
Is this backwards compatible?

I pulled the branch to test it out and saw some errors with existing cohorts:
```
An error has occurred: Cannot read properties of undefined (reading '0')
```
A new cohort worked fine.

Maybe my machine was in a weird state when I switched, but just wanted to double check.

2023-09-19 12:35 UTC, tjennison-google commented
> Is this backwards compatible?
> 
> I pulled the branch to test it out and saw some errors with existing cohorts:
> 
> ```
> An error has occurred: Cannot read properties of undefined (reading '0')
> ```
> 
> A new cohort worked fine.
> 
> Maybe my machine was in a weird state when I switched, but just wanted to double check.

No, it's not. I haven't been making an effort to maintain backwards compatibility yet.

2023-09-19 13:30 UTC, marikomedlock commented
> > Is this backwards compatible?
> 
> No, it's not. I haven't been making an effort to maintain backwards compatibility yet.

OK, I think we need to give VUMC and folks on the Verily side (product + solutions) a heads up if this version forward will make all their existing data unusable.

2023-09-20 19:13 UTC, tjennison-google commented
> > > Is this backwards compatible?
> > 
> > 
> > No, it's not. I haven't been making an effort to maintain backwards compatibility yet.
> 
> OK, I think we need to give VUMC and folks on the Verily side (product + solutions) a heads up if this version forward will make all their existing data unusable.

This will be backwards compatible after my previous PR. Can you re-approve?

2023-09-20 20:07 UTC, marikomedlock approved these changes

2023-09-20 20:37 UTC, merged