Add Physical Measurements configs to aouRT underlay
DataBiosphere/tanagra pull request #713
Opened 2024-02-07 04:38 UTC by dolbeew

Add entities for blood pressure, bmi, heart rate, height, hip circumference, waist circumference and weight.

![Screenshot 2024-02-06 at 11 37 55 PM](https://github.com/DataBiosphere/tanagra/assets/40036095/55e93e30-41ea-4f19-ad2c-1a6a18fd41a5)

2024-02-07 13:49 UTC, chenchals commented on underlay/src/main/resources/config/datamapping/aouRT/entity/bloodPressureOccurrence/all.sql
Great!

2024-02-07 14:02 UTC, chenchals requested changes
Need the following changes:
- I did not see indexed tables for `SC2023Q3R2` dataset for physical measurements 
  -  underlay/src/main/resources/config/underlay/aouSC2023Q3R2/ui.json
  - underlay/src/main/resources/config/underlay/aouSR2023Q3R2/underlay.json
- Run indexing build for Controlled tier also 
- I am guessing, you have deployed to local docker in AoU to check the UI

2024-02-07 14:16 UTC, chenchals commented on underlay/src/main/resources/config/datamapping/aouRT/entity/bloodPressureOccurrence/entity.json
> +  "name": "bloodPressure",
change to
"name": "bloodPressureOccurrence",

2024-02-07 16:02 UTC, freemabd approved these changes
Looks good. Just a few comments on folder names.

2024-02-07 18:03 UTC, chenchals requested changes
Need to have changes to be added/modified for physical measurements
- underlay/aouSC2023Q3R2/ui.json
- underlay/aouSC2023Q3R2/underlay.json

2024-02-08 02:57 UTC, dolbeew commented
I renamed all entity folders to drop 'Occurrence.' Also added all entities and groups to the aouCT underlay and tested locally in the Workbench after running indexing.

2024-02-08 18:12 UTC, chenchals approved these changes
Thank you for the changes!

2024-02-08 19:05 UTC, merged